Add gcc-multilib
In file included from /usr/include/limits.h:27:0,
                 from /usr/lib/gcc/i686-linux-gnu/4.7/include-fixed/limits.h:169,
                 from /usr/lib/gcc/i686-linux-gnu/4.7/include-fixed/syslimits.h:7,
                 from /usr/lib/gcc/i686-linux-gnu/4.7/include-fixed/limits.h:34,
                 from /opt/rustlang/src/compiler-rt/lib/builtins/int_lib.h:44,
                 from /opt/rustlang/src/compiler-rt/lib/builtins/absvdi2.c:15:
/usr/include/features.h:324:26: fatal error: bits/predefs.h: No such file or directory
compilation terminated.

shows up in compiler barf.

Error may be from missing gcc-multilib, or perhaps g++-multilib.

That run took:

real    40m20.969s
user    0m2.572s
sys     0m0.524s